export function getDmSuspencesQuery(documentIds: number[]): string {
  return `SELECT 
  ed.ID_DOCUMENTS,
  et.ID_ETAPTECHPROC,
  par_ge.NAMEETAP,
  ed.DATA_START,
  ed.DATA_PLAN,
  ed.DATA_REAL,
  et.SROK
FROM DM.ETAPS_DOC ed 
LEFT JOIN DM.ETAPS_TECHPROC et ON et.ID_ETAPTECHPROC = ed.ID_ETAPTECHPROC
LEFT JOIN (SELECT DISTINCT ID_ETAPTECHPROC, ID_ETAPTECHPROCPARENT FROM DM.ETAPS_OTN) eo ON eo.ID_ETAPTECHPROC = et.ID_ETAPTECHPROC
LEFT JOIN DM.G_ETAPS ge ON ge.ID_ETAP = et.ID_ETAP
LEFT JOIN DM.ETAPS_TECHPROC par_et ON par_et.ID_ETAPTECHPROC = eo.ID_ETAPTECHPROCPARENT 
LEFT JOIN DM.G_ETAPS par_ge ON par_ge.ID_ETAP = par_et.ID_ETAP 
WHERE eo.ID_ETAPTECHPROCPARENT IS NOT NULL
  AND ge.TYPE_ETAP = 7
  AND ed.ID_DOCUMENTS IN (${documentIds.join(', ')})`;
}
