-- Статусы объектов
DROP TABLE IF EXISTS equity.object_status_types CASCADE;
CREATE TABLE equity.object_status_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE equity.object_status_types
    OWNER to renovation_user;

INSERT INTO equity.object_status_types (id, name) VALUES
    (1, 'Подлежит передаче дольщику - акт не подписан'),
    (2, 'Подлежит передаче дольщику - акт подписан'),
    (3, 'Передано дольщику'),
    (4, 'Подрежит передаче городу'),
    (5, 'Передано городу'),
    (6, 'Статус не определен');

-- Типы объектов
DROP TABLE IF EXISTS equity.object_types CASCADE;
CREATE TABLE equity.object_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE equity.object_types
    OWNER to renovation_user;
INSERT INTO equity.object_types (id, name) VALUES
    (1, 'квартира'),
    (2, 'машино-место'),
    (3, 'нежилое пом.');

-- Типы предметом требований
DROP TABLE IF EXISTS equity.claim_item_types CASCADE;
CREATE TABLE equity.claim_item_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE equity.claim_item_types
    OWNER to renovation_user;
INSERT INTO equity.claim_item_types (id, name) VALUES
    (1, 'квартира'),
    (2, 'машино-место'),
    (3, 'деньги');

-- Типы операций
DROP TABLE IF EXISTS equity.operation_types CASCADE;
CREATE TABLE equity.operation_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    priority integer NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE equity.operation_types
    OWNER to renovation_user;
INSERT INTO equity.operation_types (id, name, priority) VALUES
(1, 'Акт подписан', 10),
(2, 'Дефектная ведомость открыта', 1),
(3, 'Дефектная ведомость закрыта', 2),
(4, 'Дефекты выявлены', 1),
(5, 'Запись на прием', 3),
(6, 'Заключение УРЖП запрошено', 4),
(7, 'Заключение УРЖП дано', 5),
(8, 'Выявлены признаки двойной продажи', 0);

ALTER TABLE equity.operation_types
    OWNER to renovation_user;
INSERT INTO equity.operation_types (id, name) VALUES
    (1, 'квартира'),
    (2, 'машино-место'),
    (3, 'нежилое пом.');


-- Типы источников требований
DROP TABLE IF EXISTS equity.claim_source_types CASCADE;
CREATE TABLE equity.claim_source_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    priority integer NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE equity.claim_source_types
    OWNER to renovation_user;
INSERT INTO equity.claim_source_types (id, name, priority) VALUES
    (1, 'Информация застройщика', 2),
    (2, 'РТУС', 3),
    (3, 'Обременение в ЕГРН', 4),
    (4, 'Судебное решение', 5),
    (5, 'Обращение гражданина', 1);

-- Жилые комплексы
DROP TABLE IF EXISTS equity.complexes CASCADE;
CREATE TABLE equity.complexes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    developer character varying(255),
    PRIMARY KEY (id)
);
ALTER TABLE equity.complexes
    OWNER to renovation_user;

INSERT INTO equity.complexes (id, name, developer) VALUES
    (1, 'Царицыно', 'АО "Мосотделстрой 1"'),
    (2, 'Марушкино', 'АО "Мосотделстрой 1"'),
    (3, 'Терлецкий парк', 'АО "Мосотделстрой 1"'),
    (4, 'Кокошкино', 'Фонд защиты прав дольщиков'),
    (5, 'Малыгина', 'Фонд защиты прав дольщиков'),
    (6, 'Легенда', 'Фонд защиты прав дольщиков'),
    (7, 'Троицк Е-39', 'Фонд защиты прав дольщиков'),
    (8, 'Остров Эрин', 'Фонд защиты прав дольщиков'),
    (9, 'Академ Палас', 'Фонд защиты прав дольщиков'),
    (10, 'Воскресенское', 'Фонд защиты прав дольщиков'),
    (11, 'Квартал Триумфальный', 'Фонд защиты прав дольщиков');

-- Корпуса
DROP TABLE IF EXISTS equity.buildings CASCADE;
CREATE TABLE equity.buildings
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    created_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
    updated_at timestamp with time zone,
    updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

    complex_id integer REFERENCES equity.complexes(id),
    unom bigint,
    cad_num character varying(255),

    address_short character varying(255),
    address_full character varying(255),
    address_construction character varying(255),

    is_done boolean NOT NULL DEFAULT true,

	PRIMARY KEY (id)
);
ALTER TABLE equity.buildings
    OWNER to renovation_user;


-- Объекты
DROP TABLE IF EXISTS equity.objects CASCADE;
CREATE TABLE equity.objects
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    created_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
    updated_at timestamp with time zone,
    updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

    legacy_pk character varying(255) NOT NULL,

    building_id integer NOT NULL REFERENCES equity.buildings(id),
    object_type_id integer NOT NULL REFERENCES equity.object_types(id),
    is_identified boolean NOT NULL DEFAULT true,

    cad_num character varying(255),
    unkv integer,

    rooms integer,
    floor integer,
    s_obsh numeric,
    num character varying(255),

    egrn_title_type text,
    egrn_title_date timestamp with time zone,
    egrn_title_num text,
    egrn_address text,
    egrn_position text,
    egrn_holder_name text,
    egrn_holder_full text,
    egrn_holder_type text,
    egrn_source text,
    egrn_status character varying(255),

    npp integer GENERATED ALWAYS AS (("substring"((num)::text, '\d+'::text))::integer) STORED;
	PRIMARY KEY (id)
);
CREATE INDEX idx_equity_objects_building_id ON equity.objects(building_id);
CREATE INDEX idx_equity_objects_object_type_id ON equity.objects(object_type_id);
CREATE INDEX idx_equity_objects_is_identified ON equity.objects(is_identified);
CREATE INDEX idx_equity_objects_npp ON equity.objects(npp);
ALTER TABLE equity.objects
    OWNER to renovation_user;

-- Требования
DROP TABLE IF EXISTS equity.claims CASCADE;
CREATE TABLE equity.claims
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    object_id integer NOT NULL REFERENCES equity.objects(id),

    created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    created_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
    updated_at timestamp with time zone,
    updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

    legacy_pk character varying(255) NOT NULL,
    legacy_fk_object character varying(255) NOT NULL,
    claim_item_type_id integer NOT NULL REFERENCES equity.claim_item_types(id),
    claim_source_type_id integer NOT NULL REFERENCES equity.claim_source_types(id),

    claim_registry_date timestamp with time zone,
    claim_registry_num character varying(255),
    creditor_registry_num character varying(255),    
    basis text,
    legal_act text,
    change_basis text,
    subject text,
    sum_paid numeric,
    sum_unpaid numeric,
    sum_damages numeric,

    creditor_name text,
    creditor_documents text,
    creditor_address text,
    creditor_contacts text,
    
    claim_settlement_reason character varying(255),
    claim_settlement_date timestamp with time zone,
    claim_exclusion_reason character varying(255),
    claim_exclusion_date timestamp with time zone,

    claim_status character varying(255),
    claim_status_legacy character varying(255),
    notes text,

    identification_notes text,
    source character varying(255),

    unit character varying(50),
    section integer,
    floor integer,
    room_count integer,
    s numeric,
    section_order integer,
    num_project character varying(255),

    PRIMARY KEY (id)
);
CREATE INDEX idx_claims_object_id ON equity.claims USING btree (object_id);
CREATE INDEX idx_claims_claim_item_type_id ON equity.claims USING btree (claim_item_type_id);
CREATE INDEX idx_claims_claim_status ON equity.claims USING btree (claim_status);
CREATE INDEX idx_claims_priority ON equity.claims USING btree (priority);
ALTER TABLE equity.claims
    OWNER to renovation_user;

-- Операции
DROP TABLE IF EXISTS equity.operations CASCADE;
CREATE TABLE equity.operations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    object_id integer NOT NULL REFERENCES equity.objects(id),
    claim_id integer REFERENCES equity.claims(id),

    created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    created_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
    updated_at timestamp with time zone,
    updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

    legacy_fk_object character varying(255) NOT NULL,
    legacy_fk_claim character varying(255),
    type_id integer NOT NULL REFERENCES equity.operation_types(id),
    source character varying(255),
    date timestamp with time zone,
    notes text,
    number character varying(255),
    result character varying(255),

    PRIMARY KEY (id)
);
CREATE INDEX idx_operations_object_id ON equity.operations USING btree (object_id);
CREATE INDEX idx_operations_claim_id ON equity.operations USING btree (claim_id);
CREATE INDEX idx_operations_type_id ON equity.operations USING btree (type_id);
CREATE INDEX idx_operations_sort_order ON equity.operations USING btree (object_id, date NULLS LAST, created_at NULLS LAST, id DESC);
ALTER TABLE equity.operations
    OWNER to renovation_user;