import { cn } from '@urgp/client/shared';
import {
  Blocks,
  Bot,
  BotOff,
  BrickWall,
  BrickWallFire,
  Building2,
  CalendarCheck,
  CalendarRange,
  CalendarX,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  // CircleDollarSign,
  CircleEllipsis,
  CircleMinus,
  CircleX,
  Construction,
  Container,
  Eye,
  EyeOff,
  Frown,
  Gavel,
  Grid2X2,
  Grid2X2X,
  HardHat,
  House,
  MailX,
  RefreshCcw,
  RotateCcw,
  Scale,
  Scan,
  ScanEye,
  SquareCheck,
  SquareDashed,
} from 'lucide-react';

export const newBuildingRelocationStatus = [
  {
    value: 'Освобождено',
    label: 'Освобождено',
    icon: SquareCheck,
  },
  {
    value: 'Идет полное освобождение',
    label: 'Идет полное освобождение',
    icon: Grid2X2,
  },
  {
    value: 'Идет частичное освобождение',
    label: 'Идет частичное освобождение',
    icon: Grid2X2X,
  },
  {
    value: 'Освобождение не начато',
    label: 'Освобождение не начато',
    icon: SquareDashed,
  },
];
