DROP TABLE IF EXISTS public.adress_registry CASCADE;
CREATE TABLE public.adress_registry (
    global_id INTEGER PRIMARY KEY,
    on_territory_of_moscow BOOLEAN,
    unom INTEGER,
    address TEXT,
    simple_address TEXT,
    adm_area VARCHAR(255),
    district VARCHAR(255),
    nreg INTEGER,
    dreg DATE,
    n_fias TEXT,
    d_fias DATE,
    kladr VARCHAR(20),
    tdoc VARCHAR(255),
    ndoc VARCHAR(50),
    ddoc DATE,
    obj_type VARCHAR(255),
    adr_type VARCHAR(255),
    vid VARCHAR(255),
    sostad VARCHAR(255),
    status VARCHAR(255),
    kad_n TEXT[],
    kad_zu TEXT[],
    outline GEOMETRY,
    p0 VARCHAR(255),
    p1 VARCHAR(255),
    p2 VARCHAR(255),
    p3 VARCHAR(255),
    p4 VARCHAR(255),
    p5 VARCHAR(255),
    p6 VARCHAR(255),
    p7 VARCHAR(255),
    p90 VARCHAR(255),
    p91 VARCHAR(255),
    l1_type VARCHAR(255),
    l1_value VARCHAR(255),
    l2_type VARCHAR(255),
    l2_value VARCHAR(255),
    l3_type VARCHAR(255),
    l3_value VARCHAR(255),
    l4_type VARCHAR(255),
    l4_value VARCHAR(255),
    l5_type VARCHAR(255),
    l5_value VARCHAR(255)
);

ALTER TABLE public.adress_registry
    OWNER to renovation_user;