-- Дела
DROP TABLE IF EXISTS control.cases_ CASCADE;
CREATE TABLE control.cases_
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	class character varying(255) DEFAULT 'control-incident',
	type_id integer NOT NULL REFERENCES control.case_types(id),

	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, 
	updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	approve_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_status character varying(255) DEFAULT 'project',
	approve_date timestamp with time zone,
	approve_notes character varying(255),

	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	updated_at timestamp with time zone,

	external_cases jsonb NOT NULL DEFAULT '[]'::jsonb,
	direction_ids integer[] NOT NULL DEFAULT array[]::integer[],

	title character varying(255), -- ФИО
	notes text, -- Описание
	extra text, -- Адрес

	archive_date timestamp with time zone,
	revision integer NOT NULL DEFAULT 1,
	-- is_deleted boolean NOT NULL DEFAULT false,
	PRIMARY KEY (id)
);
ALTER TABLE control.cases_
    OWNER to renovation_user;


-- История дел
DROP TABLE IF EXISTS control.cases_history CASCADE;
CREATE TABLE control.cases_history
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	case_id integer NOT NULL, -- REFERENCES control.cases_(id) ON DELETE CASCADE,
	class character varying(255) DEFAULT 'control-incident',
	type_id integer NOT NULL REFERENCES control.case_types(id),

	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, 
	updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	approve_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_status character varying(255) DEFAULT 'project',
	approve_date timestamp with time zone,
	approve_notes character varying(255),

	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	updated_at timestamp with time zone,

	external_cases jsonb NOT NULL DEFAULT '[]'::jsonb,
	direction_ids integer[] NOT NULL DEFAULT array[]::integer[],

	title character varying(255), -- ФИО
	notes text, -- Описание
	extra text, -- Адрес

	archive_date timestamp with time zone,
	revision integer NOT NULL DEFAULT 1,
	delete_date	timestamp with time zone,
	PRIMARY KEY (id)
);
ALTER TABLE control.cases_history
    OWNER to renovation_user;



-- Операции
DROP TABLE IF EXISTS control.operations_ CASCADE;
CREATE TABLE control.operations_
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	case_id integer NOT NULL REFERENCES control.cases_(id),
	class character varying(255) DEFAULT 'stage',
	type_id integer NOT NULL REFERENCES control.operation_types(id),

	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, 
	updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	approve_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_status character varying(255) DEFAULT 'project',
	approve_date timestamp with time zone,
	approve_notes character varying(255),

	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	updated_at timestamp with time zone,

	due_date timestamp with time zone,
	done_date timestamp with time zone,

	control_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	control_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	title character varying(255), -- Номер
	notes text, -- Описание
	extra text, -- Описание изменения даты

	archive_date timestamp with time zone,
	revision integer NOT NULL DEFAULT 1,
	PRIMARY KEY (id)
);
ALTER TABLE control.operations_
    OWNER to renovation_user;


-- История операций
DROP TABLE IF EXISTS control.operations_history CASCADE;
CREATE TABLE control.operations_history
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	operation_id integer NOT NULL, -- NOT NULL REFERENCES control.operations_(id),
	case_id integer, -- NOT NULL REFERENCES control.cases_(id),
	class character varying(255) DEFAULT 'stage',
	type_id integer NOT NULL REFERENCES control.operation_types(id),

	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, 
	updated_by_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	approve_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	approve_status character varying(255) DEFAULT 'project',
	approve_date timestamp with time zone,
	approve_notes character varying(255),

	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	updated_at timestamp with time zone,

	due_date timestamp with time zone,
	done_date timestamp with time zone,

	control_from_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	control_to_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,

	title character varying(255), -- Номер
	notes text, -- Описание
	extra text, -- Описание изменения даты

	archive_date timestamp with time zone,
	revision integer NOT NULL DEFAULT 1,
	delete_date	timestamp with time zone,
	-- is_deleted boolean NOT NULL DEFAULT false,
	PRIMARY KEY (id)
);
ALTER TABLE control.operations_history
    OWNER to renovation_user;