-- Дела
DROP TABLE IF EXISTS control.cases CASCADE;
CREATE TABLE control.cases
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.cases
    OWNER to renovation_user;

-- Системные проблемы
DROP TABLE IF EXISTS control.problems CASCADE;
CREATE TABLE control.problems
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.problems
    OWNER to renovation_user;

-- Связь дел и системных проблем
DROP TABLE IF EXISTS control.connections_case_problem CASCADE;
CREATE TABLE control.connections_case_problem
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    case_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
    problem_id integer REFERENCES control.problems(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_case_problem
    OWNER to renovation_user;

-- Операции
DROP TABLE IF EXISTS control.operations CASCADE;
CREATE TABLE control.operations
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    case_id integer REFERENCES control.cases(id) ON DELETE SET NULL,
    problem_id integer REFERENCES control.problems(id) ON DELETE SET NULL,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.operations
    OWNER to renovation_user;


-- just keep those in operations maybe?
-- Поручения
-- DROP TABLE IF EXISTS control.dispatches CASCADE;
-- CREATE TABLE control.dispatches
-- (
-- 	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     case_id integer REFERENCES control.cases(id) ON DELETE SET NULL,
--     problem_id integer REFERENCES control.problems(id) ON DELETE SET NULL,
-- 	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
-- 	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
-- 	payload jsonb,
-- 	PRIMARY KEY (id)
-- );
-- ALTER TABLE control.dispatches
--     OWNER to renovation_user;

-- Направления работы
DROP TABLE IF EXISTS control.directions CASCADE;
CREATE TABLE control.directions
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
    tags character varying(255)[],
	PRIMARY KEY (id)
);
ALTER TABLE control.directions
    OWNER to renovation_user;

INSERT INTO control.directions (id, name, category, fullName, tags) VALUES 
(1,'б.общяги','УРЖП','Закрепление бывших общежитий', ARRAY['лукьянов','общежития','общяги']), 
(2,'б.служебка','УРЖП','Закрепление субаренды и служебных ордеров', ARRAY['лукьянов','аренда','служебка']), 
(3,'б.ком.найм','УРЖП','Закрепление по найму жилого помещения жилищного фонда коммерческого использования', ARRAY['лукьянов','бдд','коммерческий']), 
(4,'НСП','УРЖП','Служебный найм ГУ МВД России по г. Москве и 55 отряда Росгвардии', ARRAY['лукьянов','полиция','менты']), 
(5,'общежития','УРЖП','Найм в действующих общежитиях спец. фонда города', ARRAY['лукьянов','общежития','полиция']), 
(6,'сироты','УРЖП','Обеспечение квартирами сирот и оставшихся без попечения', ARRAY['лукьянов', 'найм']), 
(7,'дольщики','УРЖП','Обеспечение обманутых дольщиков', ARRAY['лукьянов','вкладчики', 'обманутые']),
(8,'переводы','УРЖП','Перевод из нежилья в жилье и обратно', ARRAY['лукьянов','нежилье', 'гу', 'услуга']),

(9,'постановка','УВЖУ','Постановка на жилищный учет', ARRAY['мусиенко','очередники', 'гу', 'услуга']),
(10,'ведение ж.у.','УВЖУ','Изменение учетных дел и снятие после ПРГ', ARRAY['мусиенко','очередники', 'гу', 'услуга']),
(11,'права до 1998','УВЖУ','Выдача справок о правах до 1998 года', ARRAY['мусиенко','собственность', 'гу', 'услуга']),
(12,'обеспечение','УВЖУ','Предоставление квартир или выплат очередникам', ARRAY['мусиенко','очередники', 'гу', 'услуга']),

(13,'ГУ по ДСН','УПГУ','Оформление ДСН и ДН к ним', ARRAY['курзина','соцнайм', 'социальный', 'гу', 'услуга']),
(14,'приватизация','УПГУ','Приватизация и деприватизация помещений', ARRAY['курзина','приватизация', 'собственность', 'гу', 'услуга']),
(15,'ПРГ','УПГУ','Перерегистрация учетных дел очередников', ARRAY['курзина','перерегистрация', 'очередники', 'гу', 'услуга']),

(16,'реновация','УП','Переселение в рамках программы Реновации', ARRAY['замураев','переселение', 'реновация']),
(17,'расселение','УП','Переселение вне рамок программы Реновации (аварийность, развития территорий)', ARRAY['замураев','переселение', 'аварийность']),

(18,'ресурс','УОЖП','Ведение и учет ресурса жилой площади', ARRAY['пахмутов','площадь', 'незаселенка']),
(19,'подбор','УОЖП','Подбор квартир и комнат для городских задач', ARRAY['пахмутов','подбор', 'площадь']),
(20,'выморочка','УОЖП','Оформление выморочной площади', ARRAY['пахмутов','наследство', 'площадь']);

-- Связь дел и направлений работы
DROP TABLE IF EXISTS control.connections_case_direction CASCADE;
CREATE TABLE control.connections_case_direction
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    case_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
    directiom_id integer REFERENCES control.directions(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_case_direction
    OWNER to renovation_user;

-- Связь системных проблем и направлений работы
DROP TABLE IF EXISTS control.connections_problem_direction CASCADE;
CREATE TABLE control.connections_problem_direction
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    problem_id integer REFERENCES control.problems(id) ON DELETE CASCADE,
    directiom_id integer REFERENCES control.directions(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_problem_direction
    OWNER to renovation_user;


-- Статусы дел
DROP TABLE IF EXISTS control.case_status_types CASCADE;
CREATE TABLE control.case_status_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	PRIMARY KEY (id)
);
ALTER TABLE control.case_status_types
    OWNER to renovation_user;

INSERT INTO control.case_status_types (id, name, category, fullName) VALUES 
(1, 'на утверждении', 'проект', 'Проект дела требует утверждения'),
(2, 'направлено', 'в работе', 'Направлено на рассмотрение в профильное управление'),
(3, 'в работе', 'в работе', 'Профильным управлением ведется работа над делом'),
(4, 'проект решения', 'в работе', 'Проект решения по делу ждет утверждения'),
(5, 'отклонено', 'рассмотрено', 'Наличие проблемы не подтвердилось'),
(6, 'решено', 'рассмотрено', 'Проблема устранена'),
(7, 'не решено', 'рассмотрено', 'Проблему не удалось устранить, дальнейшая работа не целесообразна'),
(8, 'запрошено заключение', 'эскалация', 'Запрошено заключение руководства по решению'),
(9, 'возвращено на доработку', 'эскалация', 'Проблема возвращена на доработку руководством');


-- Виды заявок
DROP TABLE IF EXISTS control.case_types CASCADE;
CREATE TABLE control.case_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	PRIMARY KEY (id)
);
ALTER TABLE control.case_types
    OWNER to renovation_user;

INSERT INTO control.case_types (id, name, category, fullName) VALUES 
(1, 'нарушение', 'control', 'Нарушен регламент'),
(2, 'помочь клиенту', 'control', 'Можно помочь гражданину'),
(3, 'помочь себе', 'control', 'Возможна выгода для города'),
(4, 'предложение', 'control', 'Рационализаторское предложение');