-- Дела
DROP TABLE IF EXISTS control.cases CASCADE;
CREATE TABLE control.cases
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	class character varying(255) DEFAULT 'control-incident',
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.cases
    OWNER to renovation_user;

-- Связки дел
DROP TABLE IF EXISTS control.case_connections CASCADE;
CREATE TABLE control.case_connections
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
	child_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
	parent_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
	reason character varying(255),
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.case_connections
    OWNER to renovation_user;

-- Операции
DROP TABLE IF EXISTS control.operations CASCADE;
CREATE TABLE control.operations
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	class character varying(255),
    case_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.operations
    OWNER to renovation_user;

-- Направления работы
DROP TABLE IF EXISTS control.direction_types CASCADE;
CREATE TABLE control.direction_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
    tags character varying(255)[],
	default_executor_id integer REFERENCES renovation.users(id) ON DELETE SET NULL,
	PRIMARY KEY (id)
);
ALTER TABLE control.direction_types
    OWNER to renovation_user;

INSERT INTO control.direction_types (id, name, category, fullName, tags, default_executor_id) VALUES 
(1,'б.общяги','УРЖП','Закрепление бывших общежитий', ARRAY['лукьянов','общежития','общяги'], 5), 
(2,'б.служебка','УРЖП','Закрепление субаренды и служебных ордеров', ARRAY['лукьянов','аренда','служебка'], 5), 
(3,'б.ком.найм','УРЖП','Закрепление по найму жилого помещения жилищного фонда коммерческого использования', ARRAY['лукьянов','бдд','коммерческий'], 5), 
(4,'НСП','УРЖП','Служебный найм ГУ МВД России по г. Москве и 55 отряда Росгвардии', ARRAY['лукьянов','полиция','менты'], 5), 
(5,'общежития','УРЖП','Найм в действующих общежитиях спец. фонда города', ARRAY['лукьянов','общежития','полиция'], 5), 
(6,'сироты','УРЖП','Обеспечение квартирами сирот и оставшихся без попечения', ARRAY['лукьянов', 'найм'], 5), 
(7,'дольщики','УРЖП','Обеспечение обманутых дольщиков', ARRAY['лукьянов','вкладчики', 'обманутые'], 5),
(8,'переводы','УРЖП','Перевод из нежилья в жилье и обратно', ARRAY['лукьянов','нежилье', 'гу', 'услуга'], 5),

(9,'постановка','УВЖУ','Постановка на жилищный учет', ARRAY['мусиенко','очередники', 'гу', 'услуга'], 4),
(10,'ведение ж.у.','УВЖУ','Изменение учетных дел и снятие после ПРГ', ARRAY['мусиенко','очередники', 'гу', 'услуга'], 4),
(11,'права до 1998','УВЖУ','Выдача справок о правах до 1998 года', ARRAY['мусиенко','собственность', 'гу', 'услуга'], 4),
(12,'обеспечение','УВЖУ','Предоставление квартир или выплат очередникам', ARRAY['мусиенко','очередники', 'гу', 'услуга'], 4),

(13,'ГУ по ДСН','УПГУ','Оформление ДСН и ДН к ним', ARRAY['курзина','соцнайм', 'социальный', 'гу', 'услуга'], 6),
(14,'приватизация','УПГУ','Приватизация и деприватизация помещений', ARRAY['курзина','приватизация', 'собственность', 'гу', 'услуга'], 6),
(15,'ПРГ','УПГУ','Перерегистрация учетных дел очередников', ARRAY['курзина','перерегистрация', 'очередники', 'гу', 'услуга'], 6),

(16,'реновация','УП','Переселение в рамках программы Реновации', ARRAY['замураев','переселение', 'реновация'], 41),
(17,'расселение','УП','Переселение вне рамок программы Реновации (аварийность, развития территорий)', ARRAY['замураев','переселение', 'аварийность'], 41),

(18,'ресурс','УОЖП','Ведение и учет ресурса жилой площади', ARRAY['пахмутов','площадь', 'незаселенка'], 7),
(19,'подбор','УОЖП','Подбор квартир и комнат для городских задач', ARRAY['пахмутов','подбор', 'площадь'], 7),
(20,'выморочка','УОЖП','Оформление выморочной площади', ARRAY['пахмутов','наследство', 'площадь'], 7);


-- Статусы дел
DROP TABLE IF EXISTS control.case_status_types CASCADE;
CREATE TABLE control.case_status_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	PRIMARY KEY (id)
);
ALTER TABLE control.case_status_types
    OWNER to renovation_user;

INSERT INTO control.case_status_types (id, name, category, fullName) VALUES 
(1, 'на утверждении', 'проект', 'Проект дела требует утверждения'),
(2, 'направлено', 'в работе', 'Направлено на рассмотрение в профильное управление'),
(3, 'в работе', 'в работе', 'Профильным управлением ведется работа над делом'),
(4, 'проект решения', 'в работе', 'Проект решения по делу ждет утверждения'),
(5, 'отклонено', 'рассмотрено', 'Наличие проблемы не подтвердилось'),
(6, 'решено', 'рассмотрено', 'Проблема устранена'),
(7, 'не решено', 'рассмотрено', 'Проблему не удалось устранить, дальнейшая работа не целесообразна'),
(8, 'запрошено заключение', 'эскалация', 'Запрошено заключение руководства по решению'),
(9, 'возвращено на доработку', 'эскалация', 'Проблема возвращена на доработку руководством'),
(10, 'не согласовано', 'проект', 'Отказано в согласовании проекта'),
(11, 'просрочка', 'в работе', 'Дело в работе, но срок исполнения уже истек'),
(12, 'проект', 'проект', 'Проект дела, не направленный на согласование');

-- Виды заявок
DROP TABLE IF EXISTS control.case_types CASCADE;
CREATE TABLE control.case_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	priority integer,
	auto_approve boolean DEFAULT true,
	class character varying(255) DEFAULT 'control-incident',
	PRIMARY KEY (id)
);
ALTER TABLE control.case_types
    OWNER to renovation_user;

INSERT INTO control.case_types (id, name, category, fullName) VALUES 
(1, 'нарушение', 'control-incident', 'Нарушен регламент'),
(2, 'помочь клиенту', 'control-incident', 'Можно помочь гражданину'),
(3, 'помочь себе', 'control-incident', 'Возможна выгода для города'),
(4, 'предложение', 'control-incident', 'Рационализаторское предложение'),
(5, 'проблема', 'control-problem', 'Системная проблема');


-- Типы операций
DROP TABLE IF EXISTS control.operation_types CASCADE;
CREATE TABLE control.operation_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	priority integer,
	auto_approve boolean DEFAULT true,
	class character varying(255) DEFAULT 'stage',
	PRIMARY KEY (id)
);
ALTER TABLE control.operation_types
    OWNER to renovation_user;

INSERT INTO control.operation_types (id, name, category, fullName, priority, auto_approve, class) VALUES 
(1, 'запрос', 'рассмотрение', 'Направлен запрос', 1, true, 'stage'),
(2, 'получено', 'рассмотрение', 'Получены документы', 1, true, 'stage'),
(3, 'письмо', 'рассмотрение', 'Направлено письмо', 1, true, 'stage'),
(4, 'звонок', 'рассмотрение', 'Устные разъяснения', 1, true, 'stage'),
(5, 'заявка', 'рассмотрение', 'Создана заявка', 1, true, 'stage'),
(6, 'проработка', 'рассмотрение', 'Иная операция', 1, true, 'stage'),

(7, 'отклонено (исп)', 'решение', 'По заявке не выявлено проблемы', 2, false, 'stage'),
(8, 'решено (исп)', 'решение', 'Описанная проблема решена', 2, false, 'stage'),
(9, 'нерешаемо (исп)', 'решение', 'Решить Проблему не удалось', 2, false, 'stage'),

(10, 'поручение', 'поручение', 'Поручение со сроком выполнения', 1, true, 'dispatch'),

(11, 'напоминание', 'напоминание', 'Напоминание о статусе дела', 1, true, 'reminder'),
(12, 'эскалация', 'напоминание', 'Запрошено мнение руководителя', 2, true, 'reminder');
