DROP TABLE IF EXISTS address.adress_registry CASCADE;
CREATE TABLE address.adress_registry (
    global_id INTEGER PRIMARY KEY,
    on_territory_of_moscow BOOLEAN,
    unom INTEGER,
    address TEXT,
    simple_address TEXT,
    adm_area VARCHAR(255),
    district VARCHAR(255),
    nreg INTEGER,
    dreg DATE,
    n_fias TEXT,
    d_fias DATE,
    kladr VARCHAR(20),
    tdoc VARCHAR(255),
    ndoc VARCHAR(50),
    ddoc DATE,
    obj_type VARCHAR(255),
    adr_type VARCHAR(255),
    vid VARCHAR(255),
    sostad VARCHAR(255),
    status VARCHAR(255),
    kad_n TEXT[],
    kad_zu TEXT[],
    outline GEOMETRY,
    p0 VARCHAR(255),
    p1 VARCHAR(255),
    p2 VARCHAR(255),
    p3 VARCHAR(255),
    p4 VARCHAR(255),
    p5 VARCHAR(255),
    p6 VARCHAR(255),
    p7 VARCHAR(255),
    p90 VARCHAR(255),
    p91 VARCHAR(255),
    l1_type VARCHAR(255),
    l1_value VARCHAR(255),
    l2_type VARCHAR(255),
    l2_value VARCHAR(255),
    l3_type VARCHAR(255),
    l3_value VARCHAR(255),
    l4_type VARCHAR(255),
    l4_value VARCHAR(255),
    l5_type VARCHAR(255),
    l5_value VARCHAR(255),
    street_calc TEXT,
    street_id REFERENCES address.street_registry(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone
);

ALTER TABLE address.adress_registry
    OWNER to renovation_user;


DROP TABLE IF EXISTS address.street_registry CASCADE;
CREATE TABLE address.street_registry (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_calc TEXT NOT NULL UNIQUE
);

ALTER TABLE address.street_registry
    OWNER to renovation_user;


DROP TABLE IF EXISTS address.sessions CASCADE;
CREATE TABLE address.sessions (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER REFERENCES renovation.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    is_error BOOLEAN NOT NULL DEFAULT false,
    is_done BOOLEAN NOT NULL DEFAULT false,
    type VARCHAR(255) DEFAULT 'fias-search',
    title VARCHAR(255),
    notes TEXT,
    status VARCHAR(255) DEFAULT 'pending',
    PRIMARY KEY (id)
);

ALTER TABLE address.sessions
    OWNER to renovation_user;


DROP TABLE IF EXISTS address.results CASCADE;
CREATE TABLE address.results (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    session_id INTEGER REFERENCES address.sessions(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    is_error BOOLEAN NOT NULL DEFAULT false,
    is_done BOOLEAN NOT NULL DEFAULT false,
    session_npp INTEGER,
    original_address TEXT,
    response_source VARCHAR(255),
    response JSONB,
    PRIMARY KEY (id)
);

ALTER TABLE address.results
    OWNER to renovation_user;