-- Дела
DROP TABLE IF EXISTS control.cases CASCADE;
CREATE TABLE control.cases
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.cases
    OWNER to renovation_user;

-- Системные проблемы
DROP TABLE IF EXISTS control.problems CASCADE;
CREATE TABLE control.problems
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.problems
    OWNER to renovation_user;

-- Связь дел и системных проблем
DROP TABLE IF EXISTS control.connections_case_problem CASCADE;
CREATE TABLE control.connections_case_problem
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    case_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
    problem_id integer REFERENCES control.problems(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_case_problem
    OWNER to renovation_user;

-- Операции
DROP TABLE IF EXISTS control.operations CASCADE;
CREATE TABLE control.operations
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    case_id integer REFERENCES control.cases(id) ON DELETE SET NULL,
    problem_id integer REFERENCES control.problems(id) ON DELETE SET NULL,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	payload jsonb,
	PRIMARY KEY (id)
);
ALTER TABLE control.operations
    OWNER to renovation_user;


-- just keep those in operations maybe?
-- Поручения
-- DROP TABLE IF EXISTS control.dispatches CASCADE;
-- CREATE TABLE control.dispatches
-- (
-- 	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     case_id integer REFERENCES control.cases(id) ON DELETE SET NULL,
--     problem_id integer REFERENCES control.problems(id) ON DELETE SET NULL,
-- 	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
-- 	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
-- 	payload jsonb,
-- 	PRIMARY KEY (id)
-- );
-- ALTER TABLE control.dispatches
--     OWNER to renovation_user;

-- Направления работы
DROP TABLE IF EXISTS control.directions CASCADE;
CREATE TABLE control.directions
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
    tags character varying(255)[],
	PRIMARY KEY (id)
);
ALTER TABLE control.directions
    OWNER to renovation_user;

INSERT INTO control.directions (id, name, category, fullName, tags) VALUES 
(1,'закрепление','УРЖП','Закрепление бывших общежитий и служебных ордеров', ARRAY['лукьянов','общежития','служебка']), 
(2,'ком.найм','УРЖП','Закрепление по найму жилого помещения жилищного фонда коммерческого использования', ARRAY['лукьянов','бдд','коммерческий']), 
(3,'НСП','УРЖП','Служебный найм ГУ МВД России по г. Москве и 55 отряда Росгвардии', ARRAY['лукьянов','полиция','менты']), 
(4,'общежития','УРЖП','Найм в действующих общежитиях спец. фонда города', ARRAY['лукьянов','общежития','полиция']), 
(5,'сироты','УРЖП','Обеспечение квартирами сирот и оставшихся без попечения', ARRAY['лукьянов', 'найм']), 
(6,'дольщики','УРЖП','Обеспечение обманутых дольщиков', ARRAY['лукьянов','вкладчики', 'обманутые']);

-- Связь дел и направлений работы
DROP TABLE IF EXISTS control.connections_case_direction CASCADE;
CREATE TABLE control.connections_case_direction
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    case_id integer REFERENCES control.cases(id) ON DELETE CASCADE,
    directiom_id integer REFERENCES control.directions(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_case_direction
    OWNER to renovation_user;

-- Связь системных проблем и направлений работы
DROP TABLE IF EXISTS control.connections_problem_direction CASCADE;
CREATE TABLE control.connections_problem_direction
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp with time zone DEFAULT (now())::timestamp(0) with time zone,
    deleted_at timestamp with time zone,
    problem_id integer REFERENCES control.problems(id) ON DELETE CASCADE,
    directiom_id integer REFERENCES control.directions(id) ON DELETE CASCADE,
	author_id integer REFERENCES renovation.users(id) ON DELETE SET NULL, -- а не хотим ли мы своих юзеров с блекджеком?
	PRIMARY KEY (id)
);
ALTER TABLE control.connections_problem_direction
    OWNER to renovation_user;


-- Статусы дел
DROP TABLE IF EXISTS control.case_status_types CASCADE;
CREATE TABLE control.case_status_types
(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    category character varying(255),
    fullName character varying(255),
	PRIMARY KEY (id)
);
ALTER TABLE control.case_status_types
    OWNER to renovation_user;

INSERT INTO control.case_status_types (id, name, category, fullName) VALUES 
(1, 'на утверждении', 'проект', 'Проект дела требует утверждения'),
(2, 'направлено', 'в работе', 'Направлено на рассмотрение в профильное управление'),
(3, 'в работе', 'в работе', 'Профильным управлением ведется работа над делом'),
(4, 'проект решения', 'в работе', 'Проект решения по делу ждет утверждения'),
(5, 'отклонено', 'рассмотрено', 'Наличие проблемы не подтвердилось'),
(6, 'решено', 'рассмотрено', 'Проблема устранена'),
(7, 'не решено', 'рассмотрено', 'Проблему не удалось устранить, дальнейшая работа не целесообразна'),
(8, 'запрошено заключение', 'эскалация', 'Запрошено заключение руководства по решению'),
(9, 'возвращено на доработку', 'эскалация', 'Проблема возвращена на доработку руководством');