DROP TABLE IF EXISTS address.adress_registry CASCADE;
CREATE TABLE address.adress_registry (
    global_id INTEGER PRIMARY KEY,
    on_territory_of_moscow BOOLEAN,
    unom INTEGER,
    address TEXT,
    simple_address TEXT,
    adm_area VARCHAR(255),
    district VARCHAR(255),
    nreg INTEGER,
    dreg DATE,
    n_fias TEXT,
    d_fias DATE,
    kladr VARCHAR(20),
    tdoc VARCHAR(255),
    ndoc VARCHAR(50),
    ddoc DATE,
    obj_type VARCHAR(255),
    adr_type VARCHAR(255),
    vid VARCHAR(255),
    sostad VARCHAR(255),
    status VARCHAR(255),
    kad_n TEXT[],
    kad_zu TEXT[],
    outline GEOMETRY,
    p0 VARCHAR(255),
    p1 VARCHAR(255),
    p2 VARCHAR(255),
    p3 VARCHAR(255),
    p4 VARCHAR(255),
    p5 VARCHAR(255),
    p6 VARCHAR(255),
    p7 VARCHAR(255),
    p90 VARCHAR(255),
    p91 VARCHAR(255),
    l1_type VARCHAR(255),
    l1_value VARCHAR(255),
    l2_type VARCHAR(255),
    l2_value VARCHAR(255),
    l3_type VARCHAR(255),
    l3_value VARCHAR(255),
    l4_type VARCHAR(255),
    l4_value VARCHAR(255),
    l5_type VARCHAR(255),
    l5_value VARCHAR(255),
    street_calc TEXT,
    street_id REFERENCES address.street_registry(id) ON DELETE SET NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone
);

CREATE INDEX idx_address_registry_fias_guid
    ON address.address_registry USING btree
    (n_fias COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

ALTER TABLE address.adress_registry
    OWNER to renovation_user;


DROP TABLE IF EXISTS address.street_registry CASCADE;
CREATE TABLE address.street_registry (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_calc TEXT NOT NULL UNIQUE
);

ALTER TABLE address.street_registry
    OWNER to renovation_user;










DROP TABLE IF EXISTS address.sessions CASCADE;
CREATE TABLE address.sessions (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER REFERENCES renovation.users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    type VARCHAR(255) DEFAULT 'fias-search',
    title VARCHAR(255),
    notes TEXT,
    -- is_error BOOLEAN NOT NULL DEFAULT false,
    -- is_done BOOLEAN NOT NULL DEFAULT false,
    -- status VARCHAR(255) DEFAULT 'pending',
    PRIMARY KEY (id)
);

ALTER TABLE address.sessions
    OWNER to renovation_user;



DROP TABLE IF EXISTS address.results CASCADE;
CREATE TABLE address.results (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    session_id INTEGER REFERENCES address.sessions(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    is_error BOOLEAN NOT NULL DEFAULT false,
    is_done BOOLEAN NOT NULL DEFAULT false,
    session_npp INTEGER,
    original_address TEXT,
    response_source VARCHAR(255),
    confidence VARCHAR(255) DEFAULT 'medium',

    unom INTEGER, -- needs extra hydration
    full_address TEXT,
    postal INTEGER,
    cad_num TEXT, 
    house_cad_num TEXT,

    -- okato TEXT, -- BIGTINT
    -- oktmo TEXT, -- BIGINT
    -- oktmo_budget TEXT, -- BIGINT
    -- ifns_fl TEXT, -- INTEGER
    -- ifns_ul TEXT, -- INTEGER

    fias_id BIGINT,
    fias_guid TEXT,
    fias_path TEXT,
    fias_level INTEGER,
    fias_is_active BOOLEAN,

    -- levels 6,7,8
    street_name TEXT,
    street_level INTEGER,
    street_type TEXT,
    street_fias_id BIGINT,
    street_fias_guid TEXT,
    street_kladr TEXT,

    -- level 10
    house_name TEXT,
    house_num TEXT,
    house_type TEXT,
    house_add_num_1 TEXT,
    house_add_type_1 TEXT,
    house_add_num_2 TEXT,
    house_add_type_2 TEXT,
    house_fias_id BIGINT,
    house_fias_guid TEXT,

    -- level 11
    apartment_num TEXT,
    apartment_type TEXT,
    apartment_fias_id BIGINT,
    apartment_fias_guid TEXT,

    response JSONB,

    PRIMARY KEY (id)
);

CREATE INDEX idx_results_fias_guid
    ON address.results USING btree
    (house_fias_guid COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX idx_results_cad_num
    ON address.results USING btree
    (cad_num COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

ALTER TABLE address.results
    OWNER to renovation_user;
 
 
DROP TABLE IF EXISTS address.oks_unoms CASCADE;
CREATE TABLE address.oks_unoms (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
    unom INTEGER,
    cad_num TEXT,
    PRIMARY KEY (id)
);

CREATE INDEX idx_oks_cad_num
    ON address.results USING btree
    (cad_num COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

ALTER TABLE address.oks_unoms
    OWNER to renovation_user;


DROP TABLE IF EXISTS address.rates CASCADE;
CREATE TABLE address.rates (
    id INTEGER GENERATED ALWAYS AS IDENTITY,
 source VARCHAR(255),
 amount INTEGER,
 created_at TIMESTAMP WITH TIME ZONE DEFAULT (now())::timestamp(0) with time zone,
    PRIMARY KEY (id)
);

ALTER TABLE address.rates
    OWNER to renovation_user;