export const slimCasesUnauthorizedColumns = `
"id",
"date",
"time",
"serviceId",
"serviceName",
"propertyType",
"departmentId",
"departmentName",
"zamId",
"zamName",
"status",
"bookingCode",
"bookingSource",
"hasTechnicalProblems",
"isTechnical",
"gradeSource",
"grade",
"gradeComment",
"clientId",
'Данные скрыты' as "clientFio",
"clientType",
"operatorFio",
"operatorLink",
"operatorSurveyConsultationType",
"serviceFullName",
"operatorSurveyDate",
"clientSurveyDate"
`;

export const detailedCasesUnauthorizedColumns = `
"id",
"date",
"time",
"serviceId",
"serviceName",
"propertyType",
"departmentId",
"departmentName",
"zamId",
"zamName",
"status",
"bookingCode",
"bookingSource",
"hasTechnicalProblems",
"isTechnical",
"gradeSource",
"grade",
"gradeComment",
"clientId",
'Данные скрыты' as "clientFio",
"clientType",
"operatorFio",
"operatorSurveyDate",
"clientSurveyDate",
"bookingId",
"bookingDate",
"bookingResource",
'Данные скрыты' as "deputyFio",
'Данные скрыты' as "participantFio",
'Данные скрыты' as "orgName",
'Данные скрыты' as "phone",
'Данные скрыты' as "email",
"problemAudio",
"problemVideo",
"problemConnection",
"problemTech",
"vksSearchSpeed",
"operatorLink",
"problemSummary",
null as "privatizationAddress",
null as "contractNumber",
null as "letterNumber",
null as "flsNumber",
"operatorSurveyId",
"operatorSurveyStatus",
"operatorSurveyExtralinkId",
"operatorSurveyExtralinkUrl",
"operatorSurveyConsultationType",
"operatorSurveyIsHousing",
"operatorSurveyIsClient",
'Данные скрыты' as "operatorSurveyAddress",
"operatorSurveyRelation",
"operatorSurveyDocType",
"operatorSurveyDocDate",
"operatorSurveyDocNum",
"operatorSurveyDepartment",
"operatorSurveySummary",
"operatorSurveyMood",
"operatorSurveyNeedsAnswer",
"operatorSurveyProblems",
"operatorSurveyInfoSource",
"clientSurveyId",
"clientSurveyStatus",
"clientSurveyExtralinkId",
"clientSurveyExtralinkUrl",
"clientSurveyJoined",
"clientSurveyConsultationReceived",
"serviceFullName",
"departmentFullName",
"zamFullName"
`;
