/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OldbuildingsImport } from './routes/oldbuildings'
import { Route as RenovationRouteImport } from './routes/renovation/route'
import { Route as RenovationIndexImport } from './routes/renovation/index'
import { Route as RenovationOldbuildingsImport } from './routes/renovation/oldbuildings'

// Create Virtual Routes

const MapLazyImport = createFileRoute('/map')()
const BticalcLazyImport = createFileRoute('/bticalc')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MapLazyRoute = MapLazyImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))

const BticalcLazyRoute = BticalcLazyImport.update({
  path: '/bticalc',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bticalc.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const OldbuildingsRoute = OldbuildingsImport.update({
  path: '/oldbuildings',
  getParentRoute: () => rootRoute,
} as any)

const RenovationRouteRoute = RenovationRouteImport.update({
  path: '/renovation',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RenovationIndexRoute = RenovationIndexImport.update({
  path: '/',
  getParentRoute: () => RenovationRouteRoute,
} as any)

const RenovationOldbuildingsRoute = RenovationOldbuildingsImport.update({
  path: '/oldbuildings',
  getParentRoute: () => RenovationRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/renovation': {
      preLoaderRoute: typeof RenovationRouteImport
      parentRoute: typeof rootRoute
    }
    '/oldbuildings': {
      preLoaderRoute: typeof OldbuildingsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/bticalc': {
      preLoaderRoute: typeof BticalcLazyImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      preLoaderRoute: typeof MapLazyImport
      parentRoute: typeof rootRoute
    }
    '/renovation/oldbuildings': {
      preLoaderRoute: typeof RenovationOldbuildingsImport
      parentRoute: typeof RenovationRouteImport
    }
    '/renovation/': {
      preLoaderRoute: typeof RenovationIndexImport
      parentRoute: typeof RenovationRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  RenovationRouteRoute.addChildren([
    RenovationOldbuildingsRoute,
    RenovationIndexRoute,
  ]),
  OldbuildingsRoute,
  AboutLazyRoute,
  BticalcLazyRoute,
  MapLazyRoute,
])

/* prettier-ignore-end */
