export type User = {
  id: number;
  login: string;
  fio: string;
  roles: string[];
};

export type UserWithCredentials = User & {
  password: string;
  salt: string;
  tokenVersion: number;
};

export type UserTokens = {
  accessToken: string;
  refreshToken: string;
};

//  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
//  login character varying(225) NOT NULL UNIQUE,
//  fio character varying(225),
//  password varchar NOT NULL,
//  salt varchar NOT NULL DEFAULT 'some_salt',
//  refreshTokenVersion integer DEFAULT 1,
//  roles varchar[] DEFAULT array['user']::varchar[],
