CREATE OR REPLACE FUNCTION data_mos.is_valid_geo_json(p_text TEXT) RETURNS BOOLEAN AS $$
BEGIN
    PERFORM ST_GeomFromGeoJSON(p_text);
    RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql IMMUTABLE;