import * as https from 'https'; // Import https module

export const TELETRIBE_HTTP_OPTIONS = {
  baseURL: 'https://reports.teletribe.ru/rs/backend/',
  headers: {
    accept: 'application/json, text/plain, */*',
    'accept-language': 'ru-RU,ru;q=0.9',
    'user-agent':
      'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36',
    'content-type': 'application/x-www-form-urlencoded',
  },
  httpsAgent: new https.Agent({
    rejectUnauthorized: false,
    keepAlive: true,
  }),
};

export const HOTLINE_REPORT_DATA = {
  'data[id]': 5794,
  'data[db_alias]': 'statdb',
  // 'data[idReport]': null,
  // 'data[requestId]': 1771531962005, << Date.now() - UNIX timestamp?
  'data[variables][0][varName]': 'ip_begin',
  'data[variables][0][label]': 'Начало+периода',
  'data[variables][0][id]': 3,
  // 'data[variables][0][value]': '18.02.2026',
  'data[variables][0][options]': null,
  'data[variables][0][required]': 1,
  'data[variables][0][conditions]': null,
  'data[variables][1][varName]': 'ip_end',
  'data[variables][1][label]': 'Конец+периода',
  'data[variables][1][id]': 3,
  // 'data[variables][1][value]': '19.02.2026',
  'data[variables][1][options]': null,
  'data[variables][1][required]': 1,
  'data[variables][1][conditions]': null,
  'data[sortBy]': null,
  'data[projectId]': 'corebo00000000000odiudnsgl1fukug',
  'data[columns][0][ID]': 260287,
  'data[columns][0][ENG_NAME]': 'SESSION_ID',
  'data[columns][0][RUS_NAME]': 'ID+звонка',
  'data[columns][0][SORT_ORDER]': 10,
  'data[columns][0][EXCEL_TYPE]': 'string',
  'data[columns][0][BROWSER_WIDTH]': null,
  'data[columns][0][show]': 1,
  'data[columns][1][ID]': 260288,
  'data[columns][1][ENG_NAME]': 'ABONENT',
  'data[columns][1][RUS_NAME]': 'АОН',
  'data[columns][1][SORT_ORDER]': 20,
  'data[columns][1][EXCEL_TYPE]': 'string',
  'data[columns][1][BROWSER_WIDTH]': null,
  'data[columns][1][show]': 1,
  'data[columns][2][ID]': 260289,
  'data[columns][2][ENG_NAME]': 'LINE_CALL',
  'data[columns][2][RUS_NAME]': 'Откуда+поступил+звонок',
  'data[columns][2][SORT_ORDER]': 30,
  'data[columns][2][EXCEL_TYPE]': 'string',
  'data[columns][2][BROWSER_WIDTH]': null,
  'data[columns][2][show]': 1,
  'data[columns][3][ID]': 260290,
  'data[columns][3][ENG_NAME]': 'CALL_DATE',
  'data[columns][3][RUS_NAME]': 'Дата+поступления+звонка+в+КЦ',
  'data[columns][3][SORT_ORDER]': 40,
  'data[columns][3][EXCEL_TYPE]': 'string',
  'data[columns][3][BROWSER_WIDTH]': null,
  'data[columns][3][show]': 1,
  'data[columns][4][ID]': 260291,
  'data[columns][4][ENG_NAME]': 'CALL_TIME',
  'data[columns][4][RUS_NAME]': 'Время+поступления+звонка+в+КЦ',
  'data[columns][4][SORT_ORDER]': 50,
  'data[columns][4][EXCEL_TYPE]': 'string',
  'data[columns][4][BROWSER_WIDTH]': null,
  'data[columns][4][show]': 1,
  'data[columns][5][ID]': 260292,
  'data[columns][5][ENG_NAME]': 'SPEAKINGTIME_OP',
  'data[columns][5][RUS_NAME]': 'Длительность+разговора,+сек',
  'data[columns][5][SORT_ORDER]': 60,
  'data[columns][5][EXCEL_TYPE]': 'string',
  'data[columns][5][BROWSER_WIDTH]': null,
  'data[columns][5][show]': 1,
  'data[columns][6][ID]': 260293,
  'data[columns][6][ENG_NAME]': 'WAITTIME',
  'data[columns][6][RUS_NAME]': 'Длительность+ожидания+в+очереди',
  'data[columns][6][SORT_ORDER]': 70,
  'data[columns][6][EXCEL_TYPE]': 'string',
  'data[columns][6][BROWSER_WIDTH]': null,
  'data[columns][6][show]': 1,
  'data[columns][7][ID]': 260294,
  'data[columns][7][ENG_NAME]': 'CNT_HOLD_ALL',
  'data[columns][7][RUS_NAME]': 'Кол-во+постановок+на+HOLD',
  'data[columns][7][SORT_ORDER]': 80,
  'data[columns][7][EXCEL_TYPE]': 'string',
  'data[columns][7][BROWSER_WIDTH]': null,
  'data[columns][7][show]': 1,
  'data[columns][8][ID]': 260295,
  'data[columns][8][ENG_NAME]': 'HOLD_TIME',
  'data[columns][8][RUS_NAME]': 'Общее+время+HOLD',
  'data[columns][8][SORT_ORDER]': 90,
  'data[columns][8][EXCEL_TYPE]': 'string',
  'data[columns][8][BROWSER_WIDTH]': null,
  'data[columns][8][show]': 1,
  'data[columns][9][ID]': 260296,
  'data[columns][9][ENG_NAME]': 'USER_LOGIN',
  'data[columns][9][RUS_NAME]': 'Логин+оператора',
  'data[columns][9][SORT_ORDER]': 100,
  'data[columns][9][EXCEL_TYPE]': 'string',
  'data[columns][9][BROWSER_WIDTH]': null,
  'data[columns][9][show]': 1,
  'data[columns][10][ID]': 260297,
  'data[columns][10][ENG_NAME]': 'OPERATOR_FIO',
  'data[columns][10][RUS_NAME]': 'ФИО+оператора',
  'data[columns][10][SORT_ORDER]': 110,
  'data[columns][10][EXCEL_TYPE]': 'string',
  'data[columns][10][BROWSER_WIDTH]': null,
  'data[columns][10][show]': 1,
  'data[columns][11][ID]': 260298,
  'data[columns][11][ENG_NAME]': 'KAK_OBRASCHATSYA',
  'data[columns][11][RUS_NAME]': 'Имя',
  'data[columns][11][SORT_ORDER]': 120,
  'data[columns][11][EXCEL_TYPE]': 'string',
  'data[columns][11][BROWSER_WIDTH]': null,
  'data[columns][11][show]': 1,
  'data[columns][12][ID]': 260299,
  'data[columns][12][ENG_NAME]': 'TEMATICA',
  'data[columns][12][RUS_NAME]': 'Тема+вопроса',
  'data[columns][12][SORT_ORDER]': 130,
  'data[columns][12][EXCEL_TYPE]': 'string',
  'data[columns][12][BROWSER_WIDTH]': null,
  'data[columns][12][show]': 1,
  'data[columns][13][ID]': 260300,
  'data[columns][13][ENG_NAME]': 'KLIENT',
  'data[columns][13][RUS_NAME]': 'Клиент',
  'data[columns][13][SORT_ORDER]': 140,
  'data[columns][13][EXCEL_TYPE]': 'string',
  'data[columns][13][BROWSER_WIDTH]': null,
  'data[columns][13][show]': 1,
  'data[columns][14][ID]': 260301,
  'data[columns][14][ENG_NAME]': 'ADRES_REGISTRACII',
  'data[columns][14][RUS_NAME]': 'Адрес+регистрации+по+м/ж',
  'data[columns][14][SORT_ORDER]': 150,
  'data[columns][14][EXCEL_TYPE]': 'string',
  'data[columns][14][BROWSER_WIDTH]': null,
  'data[columns][14][show]': 1,
  'data[columns][15][ID]': 260302,
  'data[columns][15][ENG_NAME]': 'OTNOSHENIYA_S_MOSKVOY',
  'data[columns][15][RUS_NAME]':
    'Отношения+с+Москвой+(№+учетного+дела/договора',
  'data[columns][15][SORT_ORDER]': 160,
  'data[columns][15][EXCEL_TYPE]': 'string',
  'data[columns][15][BROWSER_WIDTH]': null,
  'data[columns][15][show]': 1,
  'data[columns][16][ID]': 260303,
  'data[columns][16][ENG_NAME]': 'KAKOY_DOCUMENT',
  'data[columns][16][RUS_NAME]': 'По+содержанию+какого+документа+вопрос',
  'data[columns][16][SORT_ORDER]': 170,
  'data[columns][16][EXCEL_TYPE]': 'string',
  'data[columns][16][BROWSER_WIDTH]': null,
  'data[columns][16][show]': 1,
  'data[columns][17][ID]': 260304,
  'data[columns][17][ENG_NAME]': 'DATA_DOCUMENTA',
  'data[columns][17][RUS_NAME]': 'Дата+документа',
  'data[columns][17][SORT_ORDER]': 180,
  'data[columns][17][EXCEL_TYPE]': 'string',
  'data[columns][17][BROWSER_WIDTH]': null,
  'data[columns][17][show]': 1,
  'data[columns][18][ID]': 260305,
  'data[columns][18][ENG_NAME]': 'NOMER_DOCUMENTA',
  'data[columns][18][RUS_NAME]': 'Номер+документа',
  'data[columns][18][SORT_ORDER]': 190,
  'data[columns][18][EXCEL_TYPE]': 'string',
  'data[columns][18][BROWSER_WIDTH]': null,
  'data[columns][18][show]': 1,
  'data[columns][19][ID]': 260306,
  'data[columns][19][ENG_NAME]': 'UPRAVLENIE',
  'data[columns][19][RUS_NAME]': 'Управление',
  'data[columns][19][SORT_ORDER]': 200,
  'data[columns][19][EXCEL_TYPE]': 'string',
  'data[columns][19][BROWSER_WIDTH]': null,
  'data[columns][19][show]': 1,
  'data[columns][20][ID]': 260307,
  'data[columns][20][ENG_NAME]': 'OTKUDA_UZNALI',
  'data[columns][20][RUS_NAME]': 'Откуда+узнали+о+Горячей+Линии+ДГИ',
  'data[columns][20][SORT_ORDER]': 210,
  'data[columns][20][EXCEL_TYPE]': 'string',
  'data[columns][20][BROWSER_WIDTH]': null,
  'data[columns][20][show]': 1,
  'data[columns][21][ID]': 260308,
  'data[columns][21][ENG_NAME]': 'OPISANIE_VOPROSA',
  'data[columns][21][RUS_NAME]': 'Описание+вопроса',
  'data[columns][21][SORT_ORDER]': 220,
  'data[columns][21][EXCEL_TYPE]': 'string',
  'data[columns][21][BROWSER_WIDTH]': null,
  'data[columns][21][show]': 1,
  'data[columns][22][ID]': 260309,
  'data[columns][22][ENG_NAME]': 'HARAKTER_VOPROSA',
  'data[columns][22][RUS_NAME]': 'Характер+вопроса',
  'data[columns][22][SORT_ORDER]': 230,
  'data[columns][22][EXCEL_TYPE]': 'string',
  'data[columns][22][BROWSER_WIDTH]': null,
  'data[columns][22][show]': 1,
  'data[columns][23][ID]': 260310,
  'data[columns][23][ENG_NAME]': 'PERS_DANNYE',
  'data[columns][23][RUS_NAME]':
    'Вопрос+требует+разглашения+персональных+данных',
  'data[columns][23][SORT_ORDER]': 240,
  'data[columns][23][EXCEL_TYPE]': 'string',
  'data[columns][23][BROWSER_WIDTH]': null,
  'data[columns][23][show]': 1,
  'data[columns][24][ID]': 260311,
  'data[columns][24][ENG_NAME]': 'VOPROS_NE_V_KOMPETENCII',
  'data[columns][24][RUS_NAME]': 'Вопрос+не+в+компетенции',
  'data[columns][24][SORT_ORDER]': 250,
  'data[columns][24][EXCEL_TYPE]': 'string',
  'data[columns][24][BROWSER_WIDTH]': null,
  'data[columns][24][show]': 1,
  'data[columns][25][ID]': 260312,
  'data[columns][25][ENG_NAME]': 'OTPRAVLEN_NA_YANDEX',
  'data[columns][25][RUS_NAME]': 'Отправлен+на+Яндекс',
  'data[columns][25][SORT_ORDER]': 260,
  'data[columns][25][EXCEL_TYPE]': 'string',
  'data[columns][25][BROWSER_WIDTH]': null,
  'data[columns][25][show]': 1,
  'data[columns][26][ID]': 260313,
  'data[columns][26][ENG_NAME]': 'OBRATNIY_ZVONOK',
  'data[columns][26][RUS_NAME]': 'Обратный+звонок',
  'data[columns][26][SORT_ORDER]': 270,
  'data[columns][26][EXCEL_TYPE]': 'string',
  'data[columns][26][BROWSER_WIDTH]': null,
  'data[columns][26][show]': 1,
  'data[columns][27][ID]': 260314,
  'data[columns][27][ENG_NAME]': 'DOSROCHNOE_PREKRASCHENIE',
  'data[columns][27][RUS_NAME]':
    'Наличие+причин+для+досрочного+прекращения+разговора',
  'data[columns][27][SORT_ORDER]': 280,
  'data[columns][27][EXCEL_TYPE]': 'string',
  'data[columns][27][BROWSER_WIDTH]': null,
  'data[columns][27][show]': 1,
  'data[columns][28][ID]': 260315,
  'data[columns][28][ENG_NAME]': 'ESLI_DA',
  'data[columns][28][RUS_NAME]': 'Если+ответ+да',
  'data[columns][28][SORT_ORDER]': 290,
  'data[columns][28][EXCEL_TYPE]': 'string',
  'data[columns][28][BROWSER_WIDTH]': null,
  'data[columns][28][show]': 1,
  'data[columns][29][ID]': 260316,
  'data[columns][29][ENG_NAME]': 'UCHASTNIK_SVO',
  'data[columns][29][RUS_NAME]': 'Участник+СВО',
  'data[columns][29][SORT_ORDER]': 300,
  'data[columns][29][EXCEL_TYPE]': 'string',
  'data[columns][29][BROWSER_WIDTH]': null,
  'data[columns][29][show]': 1,
  'data[columns][30][ID]': 260317,
  'data[columns][30][ENG_NAME]': 'CHLEN_SEMYI_SVO',
  'data[columns][30][RUS_NAME]': 'Член+семьи+участника+СВО',
  'data[columns][30][SORT_ORDER]': 310,
  'data[columns][30][EXCEL_TYPE]': 'string',
  'data[columns][30][BROWSER_WIDTH]': null,
  'data[columns][30][show]': 1,
  'data[columns][31][ID]': 260318,
  'data[columns][31][ENG_NAME]': 'FLG_CALL_DISCONNECTION',
  'data[columns][31][RUS_NAME]': 'Инициатор+завершения+диалога',
  'data[columns][31][SORT_ORDER]': 320,
  'data[columns][31][EXCEL_TYPE]': 'string',
  'data[columns][31][BROWSER_WIDTH]': null,
  'data[columns][31][show]': 1,
  'data[columns][32][ID]': 260319,
  'data[columns][32][ENG_NAME]': 'SOUND_UUID',
  'data[columns][32][RUS_NAME]': 'Запись+диалога',
  'data[columns][32][SORT_ORDER]': 330,
  'data[columns][32][EXCEL_TYPE]': 'string',
  'data[columns][32][BROWSER_WIDTH]': null,
  'data[columns][32][show]': 1,
  'data[expiredDate]': null,
  // 'data[page]': 1, <<< pagination :(
  'data[perPage]': 100,
  'data[projectIds]': null,
  'data[showType]': null,
  method: 'show',
  service: 'reports/reports',
  interface: 'reports-show',
  // token: '7kn...mpt', << sessionId первый код из куки
};

export const HOTLINE_SCORE_REPORT_DATA = {
  'data[id]': 5816,
  'data[db_alias]': 'statdb',
  // 'data[idReport]': null,
  // 'data[requestId]': 1771583757291,
  'data[variables][0][varName]': 'ip_begin',
  'data[variables][0][label]': 'Начало+периода',
  'data[variables][0][id]': 3,
  // 'data[variables][0][value]': '19.02.2026',
  'data[variables][0][options]': null,
  'data[variables][0][required]': 1,
  'data[variables][0][conditions]': null,
  'data[variables][1][varName]': 'ip_end',
  'data[variables][1][label]': 'Конец+периода',
  'data[variables][1][id]': 3,
  // 'data[variables][1][value]': '20.02.2026',
  'data[variables][1][options]': null,
  'data[variables][1][required]': 1,
  'data[variables][1][conditions]': null,
  'data[sortBy]': null,
  'data[projectId]': 'corebo00000000000odiudnsgl1fukug',
  'data[columns][0][ID]': 260584,
  'data[columns][0][ENG_NAME]': 'CALL_DATE_TIME',
  'data[columns][0][RUS_NAME]': 'Дата+и+время+звонка',
  'data[columns][0][SORT_ORDER]': 10,
  'data[columns][0][EXCEL_TYPE]': 'string',
  'data[columns][0][BROWSER_WIDTH]': null,
  'data[columns][0][show]': 1,
  'data[columns][1][ID]': 260585,
  'data[columns][1][ENG_NAME]': 'OPERATOR_FIO',
  'data[columns][1][RUS_NAME]': 'ФИО',
  'data[columns][1][SORT_ORDER]': 20,
  'data[columns][1][EXCEL_TYPE]': 'string',
  'data[columns][1][BROWSER_WIDTH]': null,
  'data[columns][1][show]': 1,
  'data[columns][2][ID]': 260586,
  'data[columns][2][ENG_NAME]': 'USER_LOGIN',
  'data[columns][2][RUS_NAME]': 'логин+оператора',
  'data[columns][2][SORT_ORDER]': 30,
  'data[columns][2][EXCEL_TYPE]': 'string',
  'data[columns][2][BROWSER_WIDTH]': null,
  'data[columns][2][show]': 1,
  'data[columns][3][ID]': 260587,
  'data[columns][3][ENG_NAME]': 'AON',
  'data[columns][3][RUS_NAME]': 'АОН',
  'data[columns][3][SORT_ORDER]': 40,
  'data[columns][3][EXCEL_TYPE]': 'string',
  'data[columns][3][BROWSER_WIDTH]': null,
  'data[columns][3][show]': 1,
  'data[columns][4][ID]': 260588,
  'data[columns][4][ENG_NAME]': 'RATING_1_QUESTION',
  'data[columns][4][RUS_NAME]': 'Вопрос+1',
  'data[columns][4][SORT_ORDER]': 50,
  'data[columns][4][EXCEL_TYPE]': 'string',
  'data[columns][4][BROWSER_WIDTH]': null,
  'data[columns][4][show]': 1,
  'data[columns][5][ID]': 260589,
  'data[columns][5][ENG_NAME]': 'TEXT_2_QUESTION',
  'data[columns][5][RUS_NAME]': 'Сообщение+для+контроля+качества',
  'data[columns][5][SORT_ORDER]': 60,
  'data[columns][5][EXCEL_TYPE]': 'string',
  'data[columns][5][BROWSER_WIDTH]': null,
  'data[columns][5][show]': 1,
  'data[columns][6][ID]': 260590,
  'data[columns][6][ENG_NAME]': 'SESSION_ID',
  'data[columns][6][RUS_NAME]': 'id+звонка',
  'data[columns][6][SORT_ORDER]': 70,
  'data[columns][6][EXCEL_TYPE]': 'string',
  'data[columns][6][BROWSER_WIDTH]': null,
  'data[columns][6][show]': 1,
  'data[columns][7][ID]': 260591,
  'data[columns][7][ENG_NAME]': 'SOUND',
  'data[columns][7][RUS_NAME]': 'Прослушать',
  'data[columns][7][SORT_ORDER]': 80,
  'data[columns][7][EXCEL_TYPE]': 'string',
  'data[columns][7][BROWSER_WIDTH]': null,
  'data[columns][7][show]': 1,
  'data[expiredDate]': null,
  // 'data[page]': 1,
  'data[perPage]': 100,
  'data[projectIds]': null,
  'data[showType]': null,
  method: 'show',
  service: 'reports/reports',
  interface: 'reports-show',
  // token: '8nf929vm29jb5thqls5gprtvsd',
};

export const OUTBOUND_REPORT_DATA = {
  'data[id]': 1696,
  'data[db_alias]': 'statdb',
  // 'data[idReport]': null,
  // 'data[requestId]': 1771584239812,
  'data[variables][0][varName]': 'begin',
  'data[variables][0][label]': 'Начало+периода',
  'data[variables][0][id]': 3,
  // 'data[variables][0][value]': '19.02.2026',
  'data[variables][0][options]': null,
  'data[variables][0][required]': 1,
  'data[variables][0][conditions]': null,
  'data[variables][1][varName]': 'end',
  'data[variables][1][label]': 'Конец+периода',
  'data[variables][1][id]': 3,
  // 'data[variables][1][value]': '20.02.2026',
  'data[variables][1][options]': null,
  'data[variables][1][required]': 1,
  'data[variables][1][conditions]': null,
  'data[sortBy]': null,
  'data[projectId]': 'corebo00000000000odiudnsgl1fukug',
  'data[columns][0][ID]': 236046,
  'data[columns][0][ENG_NAME]': 'ANSWERED',
  'data[columns][0][RUS_NAME]': 'ID+звонка',
  'data[columns][0][SORT_ORDER]': 10,
  'data[columns][0][EXCEL_TYPE]': 'string',
  'data[columns][0][BROWSER_WIDTH]': null,
  'data[columns][0][show]': 1,
  'data[columns][1][ID]': 236047,
  'data[columns][1][ENG_NAME]': 'AON',
  'data[columns][1][RUS_NAME]': 'АОН',
  'data[columns][1][SORT_ORDER]': 20,
  'data[columns][1][EXCEL_TYPE]': 'string',
  'data[columns][1][BROWSER_WIDTH]': null,
  'data[columns][1][show]': 1,
  'data[columns][2][ID]': 236048,
  'data[columns][2][ENG_NAME]': 'CREATED',
  'data[columns][2][RUS_NAME]': 'Дата+и+время+совершения+звонка+',
  'data[columns][2][SORT_ORDER]': 30,
  'data[columns][2][EXCEL_TYPE]': 'string',
  'data[columns][2][BROWSER_WIDTH]': null,
  'data[columns][2][show]': 1,
  'data[columns][3][ID]': 236049,
  'data[columns][3][ENG_NAME]': 'SPEAKINGTIME',
  'data[columns][3][RUS_NAME]': 'Длительность+диалога',
  'data[columns][3][SORT_ORDER]': 40,
  'data[columns][3][EXCEL_TYPE]': 'string',
  'data[columns][3][BROWSER_WIDTH]': null,
  'data[columns][3][show]': 1,
  'data[columns][4][ID]': 236050,
  'data[columns][4][ENG_NAME]': 'CNT_HOLD_ALL',
  'data[columns][4][RUS_NAME]': 'Кол-во+постановок+на+HOLD',
  'data[columns][4][SORT_ORDER]': 50,
  'data[columns][4][EXCEL_TYPE]': 'string',
  'data[columns][4][BROWSER_WIDTH]': null,
  'data[columns][4][show]': 1,
  'data[columns][5][ID]': 236051,
  'data[columns][5][ENG_NAME]': 'HOLD_TIME',
  'data[columns][5][RUS_NAME]': 'Общее+время+HOLD+',
  'data[columns][5][SORT_ORDER]': 60,
  'data[columns][5][EXCEL_TYPE]': 'string',
  'data[columns][5][BROWSER_WIDTH]': null,
  'data[columns][5][show]': 1,
  'data[columns][6][ID]': 236052,
  'data[columns][6][ENG_NAME]': 'LOGIN',
  'data[columns][6][RUS_NAME]': 'Логин+оператора',
  'data[columns][6][SORT_ORDER]': 70,
  'data[columns][6][EXCEL_TYPE]': 'string',
  'data[columns][6][BROWSER_WIDTH]': null,
  'data[columns][6][show]': 1,
  'data[columns][7][ID]': 236053,
  'data[columns][7][ENG_NAME]': 'FIO_OP',
  'data[columns][7][RUS_NAME]': 'ФИО+оператора',
  'data[columns][7][SORT_ORDER]': 80,
  'data[columns][7][EXCEL_TYPE]': 'string',
  'data[columns][7][BROWSER_WIDTH]': null,
  'data[columns][7][show]': 1,
  'data[columns][8][ID]': 236054,
  'data[columns][8][ENG_NAME]': 'FIO',
  'data[columns][8][RUS_NAME]': 'ФИО',
  'data[columns][8][SORT_ORDER]': 90,
  'data[columns][8][EXCEL_TYPE]': 'string',
  'data[columns][8][BROWSER_WIDTH]': null,
  'data[columns][8][show]': 1,
  'data[columns][9][ID]': 236055,
  'data[columns][9][ENG_NAME]': 'EDO',
  'data[columns][9][RUS_NAME]': '№+обращения+в+ЭДО',
  'data[columns][9][SORT_ORDER]': 100,
  'data[columns][9][EXCEL_TYPE]': 'string',
  'data[columns][9][BROWSER_WIDTH]': null,
  'data[columns][9][show]': 1,
  'data[columns][10][ID]': 236056,
  'data[columns][10][ENG_NAME]': 'YANDEX',
  'data[columns][10][RUS_NAME]': 'Отправлен+на+Яндекс',
  'data[columns][10][SORT_ORDER]': 110,
  'data[columns][10][EXCEL_TYPE]': 'string',
  'data[columns][10][BROWSER_WIDTH]': null,
  'data[columns][10][show]': 1,
  'data[columns][11][ID]': 236057,
  'data[columns][11][ENG_NAME]': 'OBR_CALL',
  'data[columns][11][RUS_NAME]': 'Обратный+звонок',
  'data[columns][11][SORT_ORDER]': 120,
  'data[columns][11][EXCEL_TYPE]': 'string',
  'data[columns][11][BROWSER_WIDTH]': null,
  'data[columns][11][show]': 1,
  'data[columns][12][ID]': 236058,
  'data[columns][12][ENG_NAME]': 'SVO',
  'data[columns][12][RUS_NAME]': 'СВО',
  'data[columns][12][SORT_ORDER]': 130,
  'data[columns][12][EXCEL_TYPE]': 'string',
  'data[columns][12][BROWSER_WIDTH]': null,
  'data[columns][12][show]': 1,
  'data[columns][13][ID]': 236059,
  'data[columns][13][ENG_NAME]': 'ITOGI',
  'data[columns][13][RUS_NAME]': 'Итоги+разговора',
  'data[columns][13][SORT_ORDER]': 140,
  'data[columns][13][EXCEL_TYPE]': 'string',
  'data[columns][13][BROWSER_WIDTH]': null,
  'data[columns][13][show]': 1,
  'data[columns][14][ID]': 236060,
  'data[columns][14][ENG_NAME]': 'FLG_CALL_DISCONNECTION',
  'data[columns][14][RUS_NAME]': 'Инициатор+завершения+диалога',
  'data[columns][14][SORT_ORDER]': 150,
  'data[columns][14][EXCEL_TYPE]': 'string',
  'data[columns][14][BROWSER_WIDTH]': null,
  'data[columns][14][show]': 1,
  'data[columns][15][ID]': 236061,
  'data[columns][15][ENG_NAME]': 'SOUND_UUID',
  'data[columns][15][RUS_NAME]': 'Запись+диалога',
  'data[columns][15][SORT_ORDER]': 160,
  'data[columns][15][EXCEL_TYPE]': 'string',
  'data[columns][15][BROWSER_WIDTH]': null,
  'data[columns][15][show]': 1,
  'data[expiredDate]': null,
  // 'data[page]': 1,
  'data[perPage]': 100,
  'data[projectIds]': null,
  'data[showType]': null,
  method: 'show',
  service: 'reports/reports',
  interface: 'reports-show',
  // token: '8nf929vm29jb5thqls5gprtvsd',
};

export const reportFields: Record<
  'hotline' | 'hotline_score' | 'outbound',
  any
> = {
  hotline: HOTLINE_REPORT_DATA,
  hotline_score: HOTLINE_SCORE_REPORT_DATA,
  outbound: OUTBOUND_REPORT_DATA,
};

// curl 'https://reports.teletribe.ru/rs/backend/auth.php' \
//   -H 'Accept: application/json, text/plain, */*' \
//   -H 'Accept-Language: ru-RU,ru;q=0.9' \
//   -H 'Connection: keep-alive' \
//   -H 'Content-Type: application/x-www-form-urlencoded' \
//   -b 'varwwwhtmlrsbackendconfig=h97r8e4f9nftjcpkkhnf2vdh9l' \
//   -H 'Origin: https://reports.teletribe.ru' \
//   -H 'Referer: https://reports.teletribe.ru/rs/' \
//   -H 'Sec-Fetch-Dest: empty' \
//   -H 'Sec-Fetch-Mode: cors' \
//   -H 'Sec-Fetch-Site: same-origin' \
//   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36' \
//   -H 'X-Requested-With: XMLHttpRequest' \
//   -H 'sec-ch-ua: "Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"' \
//   -H 'sec-ch-ua-mobile: ?0' \
//   -H 'sec-ch-ua-platform: "macOS"' \
//   --data-raw 'data%5Blogin%5D=LOGIN&data%5Bpassword%5D=PWD'
