-- Клиенты
DROP TABLE IF EXISTS vks.clients CASCADE;
CREATE TABLE vks.clients
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    type VARCHAR(50) NOT NULL,
    surname VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    org_name VARCHAR(255),
    snils VARCHAR(14),
    ogrn VARCHAR(255),
    inn VARCHAR(255),

    PRIMARY KEY (id),
);
ALTER TABLE vks.clients
    OWNER to renovation_user;

-- Консультации
DROP TABLE IF EXISTS vks.cases CASCADE;
CREATE TABLE vks.cases
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    org TEXT,
    date DATE,
    time TEXT CHECK (time ~ '^\d{2}:\d{2}:\d{2}-\d{2}:\d{2}:\d{2}$'),

    service_id INTEGER,
    service_name TEXT,
    status TEXT,

    case_count INTEGER NOT NULL DEFAULT 0,
    booking_id INTEGER,
    booking_date TIMESTAMP WITH TIME ZONE,
    booking_code TEXT NOT NULL,
    booking_source TEXT,
    booking_resource TEXT,

    deputy_fio TEXT,
    phone TEXT,
    email TEXT,

    tiken_num TEXT,
    tiket_call_time TIMESTAMP WITH TIME ZONE,
    tiket_cancel_user_time TIMESTAMP WITH TIME ZONE,
    tiket_cancel_oiv_time TIMESTAMP WITH TIME ZONE,

    problem_audio TEXT,
    problem_video TEXT,
    problem_connection TEXT,
    problem_tech TEXT,
    vks_search_speed TEXT,

    online_grade INTEGER,
    online_grade_comment TEXT,

    operator_link TEXT,
    participant_fio TEXT,
    problem_summary TEXT,
    address TEXT,
    contract_number TEXT,
    letter_number TEXT,
    fls_number TEXT,
    client_id BIGINT REFERENCES vks.clients(id) ON DELETE SET NULL,

    operator_survey_id INTEGER,
    operator_survey_date TIMESTAMP WITH TIME ZONE,
    operator_survey_status VARCHAR(1),
    operator_survey_extralink_id INTEGER,
    operator_survey_extralink_url TEXT,
    operator_survey_fio TEXT,
    operator_survey_consultation_type TEXT,
    operator_survey_is_housing BOOLEAN,
    operator_survey_is_client BOOLEAN,
    operator_survey_address TEXT,
    operator_survey_relation TEXT,
    operator_survey_doc_type TEXT,
    operator_survey_doc_date TEXT,
    operator_survey_doc_num TEXT,
    operator_survey_department TEXT,
    operator_survey_summary TEXT,
    operator_survey_mood TEXT,
    operator_survey_needs_answer BOOLEAN,
    operator_survey_problems TEXT[],
    operator_survey_info_source TEXT,

    client_survey_id INTEGER,
    client_survey_date TIMESTAMP WITH TIME ZONE,
    client_survey_status VARCHAR(1),
    client_survey_extralink_id INTEGER,
    client_survey_extralink_url TEXT,
    client_survey_joined BOOLEAN,
    client_survey_consultation_received BOOLEAN,
    client_survey_grade INTEGER,
    client_survey_comment_positive TEXT,
    client_survey_comment_negative TEXT,

    is_technical BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (id),
    CONSTRAINT unique_booking_code_date UNIQUE (booking_code, date)
);
ALTER TABLE vks.cases
    OWNER to renovation_user;